name: coopartilhar
description: "Aplicativo da comunidade Flutterando para apoio aos moradores do Rio Grande do Sul"

publish_to: "none" 

version: 1.0.0+1

environment:
  flutter: "3.22.0"
  sdk: "3.4.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  core_module:
    path: ../core_module
  design_system: 
    path: ../design_system
  lottie: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/pngs/
    - assets/lotties/
